 #+TITLE: Arctos
 #+Author: Vasilis Agiomyrgianakis
 #+Options: num:nil, toc:nil H:2, html-postamble:nil
 #+DATE: <2017-08-03 Wen 02:01>
 #+LAYOUT: post
 #+CATEGORIES: sonification, visualisation, emacs, org-mode, supercollider, python, VR-AR
 #+TAGS: sonification, visualisation, emacs, org-mode, supercollider, python, VR-AR

* Arctos

*Arctos* is a research organisation which deals with sonification and visualisation of scientific data. Arctos founded by Vasilis Agiomyrgianakis, Ioannis Zannos and Fiori Anastasia Metallinou in 2016 in Athens Greece.

Our goal is to extend the visualisation and sonification methods and techniques in examining and interpret data for scientific and artistic purposes. The main goal is to experiment with new technologies in domains of Virtual reality (VR) and Augmented reality (AR), providing an application for use from scientists and educators. Our aim is to build an environment which provides an alternate way in examining, analysing as well as presenting scientific data. Additionally, in this project we are interested in exploring the aesthetic potential of data interpretation for visualisation and sonification purposes.
