 #+TITLE: about
 #+Author: Vasilis Agiomyrgianakis
 #+LAYOUT: page
 #+Options: num:nil, toc:nil H:2, html-postamble:nil



 Dr. Vasilis Agiomyrgianakis (BasMyr) is an media artist and researcher. He is also a co-founder of [[http://localhost:4000/arctos/][Arctos Organisation]]. He has gained technical skills as well as communication and collaboration skills during his work as an audiovisual artist and developer. He has enriched his knowledge and skills but also his aesthetic education through the creation of pilot projects that make use of programming for audio and video. As a PhD candidate under Dr Julio D'Escrivan, he has experimented with various tools and techniques in creating and composing audiovisual materials and works.  He uses creative coding techniques and scientific systems such as rewriting systems (L-systems) in producing and manipulate data for sonification and visualisation. He had also developed a data-driven (text-driven) sound and image synthesis techniques which he used to create audiovisual materials for his works. In addition, his portfolio of works documents his practice based research into transmediation of creative writing to audiovisual narrative, through a combination of disciplines such as sonic art, concrete music, computer graphics, filming, animation, performing elements and interactivity using existing as well as new methods and techniques through algorithmic composition. This multidisciplinary creativity concludes synthesis techniques both in sound and image, using diverse programming languages, among others. His research imperatives run along the threads of transmediation, intersemiotic translation, post - disciplinarity, and the general concerns of Human Computer Interaction (HCI). He has employed a variety of creative technologies in both fields of digital sound and visuals, through algorithmic compositions to improvisation developing software interfaces and algorithms in SuperCollider, as well as, interactive three dimensional environments in Unreal Engine 4. As an Undergraduate, he has participated in performances involving live coding of networked multi-channel audio and visual performances using SuperCollider and openFrameworks, as member of the computer arts team led by Prof. Zannos.

** EDUCATION

- 2012-2016, PhD in Music, University of Huddersfield / Department of Music Humanities and Media, UK, Supervisor: Julio D’Escrivan, Title: AudioVisual works in response to creative writing.

- 2005-2012, BA(Hons), Ionio University / Department of Audio and Visual Arts, GR, Supervisor: Ioannis Zannos, Title: A sound synthesis technique based on L-systems.

** [[http://localhost:4000/video-art/][List of works presented for PhD in the order of appearance in the thesis:]]

	- 2012, AudioVisual Haiku No.1: 05:21,
	- 2013, AudioVisual Haiku No.2: 07:21 ,
	- 2013, AudioVisual Haiku No.3: 05:21,
	- 2014, AudioVisual Epic Poetry - Nekyia: 11:21,
	- 2015, Aranea (videogame): indeterminate.

** PREVIOUS POSITIONS

2010-2011, Audiovisual creativity, Centre for Culture, Research and Documentation of the Bank of Greece/Bank of Greece, GR, Developer

** TEACHING ACTIVITIES

2012-2016, Teaching Assistant, Sound for Moving Image, Creative Coding , SMIC (Sound Music Image Collaboration), Music Humanities and Media, Huddersfield University, UK

** INVITED PRESENTATIONS

- 2009, Live audiovisual performance, Diadromi, Ionio University Festival, Corfu GR, Sound Artist,

- 2013,  AudioVisual Haiku No.1 Holmfirth Film Festival,

- 2014, AudioVisual Haiku No.3 Huddersfield  University Video Festival,

- 2017, AVARTS Festival - AKOYSMATA - Storm Trio,

- 2017, Mind the fact - Weaving voices - Πλεκτόφωνο

** Recent projects

*** [[http://localhost:4000/arctos/][Arctos]]

 sonification-visualisation of scientific data

*** Traces

 "Traces" is a real time audiovisual installation inspired by the movement of insects.

Use of creative programming languages C++, Supercollider.
Sensors: Camera, pad.
