 #+TITLE:
 #+Author: Vasilis Agiomyrgianakis
 #+LAYOUT: page
 #+Options: num:nil, toc:nil H:2, html-postamble:nil


* Strom Trio

*Storm Trio* : Σύνθεση ήχου και εικόνας σε πραγματικό χρόνο από δεδομένα Μαγνητικής Καταιγίδας
Βασίλης Αγιομυργιανάκης, Δημήτρης Μυλωνάς, Γιάννης Ζάννος, Φιορή Αναστασία Μεταλληνού
Περίληψη
Η ανακοίνωση αυτή παρουσιάζει τα αποτελέσματα έρευνας υπό εξέλιξη πάνω στην διαδραστική οπτικοποίηση και ηχοποίηση δεδομένων από αστροφυσικές μετρήσεις και προσομοιώσεις. Χρησιμοποιούνται εργαλεία ανοικτού κώδικα για σύνθεση τριδιάστατης εικόνας και ήχου σε πραγματικό χρόνο (openFrameworks και SuperCollider). Η εργασία χρησιμοποιεί δεδομένα από μετρήσεις μαγνητικής καταιγίδας από το HellENIc GeoMagnetic Array (ENIGMA). Τα αριθμητικά μεγέθη των διαδοχικών μετρήσεων έντασης του μαγνητικοού πεδίου στις τρεις διαστάσεις του χώρου (x-y-z) προβάλλονται διαδοχικά σαν σημεία σε έναν δυνητικό τριδιάστατο χώρο, και συνδέονται μεταξύ τους για να δημιουργήσουν ένα σχήμα που αντιπροσωπεύει την εξέλιξη του μαγνητικού φαινομένου στον χρόνο. Συγχρόνως, τα ίδια σημεία χρησιμοποιούνται σαν είσοδος σε ένα μοντέλο υδροδυναμικής ροής που προβάλεται σαν φόντο στην εικόνα δίνοντας μιαν εντύπωση της ροής της καταιγίδας.
Γιά την ηχοποίηση, τα δεδομένα αποτελούν παραμέτρους εισόδου σε διαδικασίες ψηφιακής σύνθεσης ήχου, σχεδιασμένες σε σειρά πειραμάτων ώστε να ανταποδίδουν την εντύπωση της αυξομοίωσης της έντασης και κατεύθυνσης του μαγνητικού πεδίου. Η έρευνα σκοπεύει στην ανάπτυξη εργλείων για την προβολή αστροφυσικών δεδομένων σε περιβάλλον εμβύθισης τύπου δυνητικής πραγματικότητας. Παρουσιάζονται αποσπάσματα από την συνολική προβολή και επιδεικνύεται ζωντανά η διαδικασία παραγωγής γραφικών και ήχου σε πραγματικό χρόνο, με κώδικα που γράφεται επί τόπου για την εξερεύνηση δυντοτήτων του συστήματος.
